### ISSUE TITLE
.git and .Idea 

### ISSUE THREAD

**Issue by fabiochelly** [markhamilton1/Synchronator#11]
Synchronator works fine on my iPhone except for one thing. It deletes everytime 2 folders located at the root of my project: .idea and .git (is it because they start with a dot?).

When I synchronize on my iphone:
- those dirs are first added locally on the iphone because they didn't exist
- then synchronator considers wrongly that the iphone previous files (without those dirs) are the last version and it deletes them just after their creation (locally and remotely!)

**Comment by fabiochelly** [comment]
Those dirs are always created then deleted each time I synchronize

**Comment by fabiochelly** [comment]
Here is the log I get. You can see that first dirs are created then deleted without reason.

****************************************
*     Dropbox File Syncronization      *
****************************************

Loading Local State

Updating From Dropbox

	Making Directory:  levcalc/.git/objects/16

	Making Directory:  levcalc/.git/objects/55

	Making Directory:  levcalc/.git/objects/58

	Making Directory:  levcalc/.git/objects/67

	Making Directory:  levcalc/.git/objects/8a

	Making Directory:  levcalc/.git/objects/9e

	Making Directory:  levcalc/.git/objects/9f

	Making Directory:  levcalc/.git/objects/b9

	Making Directory:  levcalc/.git/objects/c7
	Downloading:  levcalc/.idea/deployment.xml -- Not Found Locally
	Downloading:  levcalc/.idea/inspectionProfiles/Project_Default.xml -- Not Found Locally
	Downloading:  levcalc/.idea/levcalc.iml -- Not Found Locally
	Downloading:  levcalc/.idea/misc.xml -- Not Found Locally
	Downloading:  levcalc/.idea/modules.xml -- Not Found Locally
	Downloading:  levcalc/.idea/vcs.xml -- Not Found Locally
	Downloading:  levcalc/.git/COMMIT_EDITMSG -- Not Found Locally
	Downloading:  levcalc/.git/config -- Not Found Locally
	Downloading:  levcalc/.git/description -- Not Found Locally
	Downloading:  levcalc/.git/HEAD -- Not Found Locally
	Downloading:  levcalc/.git/hooks/applypatch-msg.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/commit-msg.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/post-update.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/pre-applypatch.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/pre-commit.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/pre-push.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/pre-rebase.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/prepare-commit-msg.sample -- Not Found Locally
	Downloading:  levcalc/.git/hooks/update.sample -- Not Found Locally
	Downloading:  levcalc/.git/index -- Not Found Locally
	Downloading:  levcalc/.git/info/exclude -- Not Found Locally
	Downloading:  levcalc/.git/logs/HEAD -- Not Found Locally
	Downloading:  levcalc/.git/logs/refs/heads/master -- Not Found Locally
	Downloading:  levcalc/.git/logs/refs/remotes/origin/master -- Not Found Locally
	Downloading:  levcalc/.git/objects/16/5b5b073a55c707cf98e1db03ed03f6475c79cd -- Not Found Locally
	Downloading:  levcalc/.git/objects/4b/28c884bcd231cb607d925303943ddb443d2ec9 -- Not Found Locally
	Downloading:  levcalc/.git/objects/55/b0dcc8dfe92394c326e289299e8d27a6cca257 -- Not Found Locally
	Downloading:  levcalc/.git/objects/58/2013069d105641a1b4420a358c0fb5a26f5f8d -- Not Found Locally
	Downloading:  levcalc/.git/objects/5a/5e256d4f08bdf731628043e6db7c1b89902977 -- Not Found Locally
	Downloading:  levcalc/.git/objects/67/16b57f6f31de256a61af06b0791dd16f55438c -- Not Found Locally
	Downloading:  levcalc/.git/objects/8a/1251af4239e365f86a39a10b2acde33df62996 -- Not Found Locally
	Downloading:  levcalc/.git/objects/91/ba864e768cba67ddb7443ece950868635d76e4 -- Not Found Locally
	Downloading:  levcalc/.git/objects/94/a25f7f4cb416c083d265558da75d457237d671 -- Not Found Locally
	Downloading:  levcalc/.git/objects/9e/eb0d75c994cd3aec82feaec7a246184ebc2e71 -- Not Found Locally
	Downloading:  levcalc/.git/objects/9f/b2bfbd3e945d929f80263f7cb96193071f8a7c -- Not Found Locally
	Downloading:  levcalc/.git/objects/a0/c130ccaf50f93c0225238bb7524d7c7d3771cd -- Not Found Locally
	Downloading:  levcalc/.git/objects/b9/d818e96f3c707ea0b317bc4f14676dcd500e96 -- Not Found Locally
	Downloading:  levcalc/.git/objects/c7/f16da42da1cfbb2b141239819250ce47059b43 -- Not Found Locally
	Downloading:  levcalc/.git/refs/heads/master -- Not Found Locally
	Downloading:  levcalc/.git/refs/remotes/origin/master -- Not Found Locally
	Downloading:  levcalc/levcalc.py -- Remote File Changed
	Downloading:  levcalc/.idea/workspace.xml -- Not Found Locally

Saving Local State

Checking For New Or Updated Local Files

Checking For Deleted Local Files
	Deleting On Dropbox:  levcalc/.idea/misc.xml  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/hooks/pre-push.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/objects/8a/1251af4239e365f86a39a10b2acde33df62996  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/8a  -- Deleting
	Deleting On Dropbox:  levcalc/.git/refs/heads/master  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/refs/heads  -- Deleting
	Deleting On Dropbox:  levcalc/.git/refs/remotes/origin/master  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/refs/remotes/origin  -- Deleting
	Remote Folder Empty: /levcalc/.git/refs/remotes  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/55/b0dcc8dfe92394c326e289299e8d27a6cca257  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/55  -- Deleting
	Deleting On Dropbox:  levcalc/.git/logs/refs/heads/master  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/logs/refs/heads  -- Deleting
	Deleting On Dropbox:  levcalc/.git/hooks/pre-commit.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/hooks/post-update.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/objects/16/5b5b073a55c707cf98e1db03ed03f6475c79cd  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/16  -- Deleting
	Deleting On Dropbox:  levcalc/.git/hooks/pre-applypatch.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/objects/4b/28c884bcd231cb607d925303943ddb443d2ec9  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/4b  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/b9/d818e96f3c707ea0b317bc4f14676dcd500e96  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/b9  -- Deleting
	Deleting On Dropbox:  levcalc/.git/hooks/applypatch-msg.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/HEAD  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/description  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.idea/deployment.xml  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.idea/inspectionProfiles/Project_Default.xml  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.idea/inspectionProfiles  -- Deleting
	Deleting On Dropbox:  levcalc/.idea/workspace.xml  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/hooks/update.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/hooks/prepare-commit-msg.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/config  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/COMMIT_EDITMSG  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/objects/a0/c130ccaf50f93c0225238bb7524d7c7d3771cd  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/a0  -- Deleting
	Deleting On Dropbox:  levcalc/.git/logs/HEAD  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/objects/9f/b2bfbd3e945d929f80263f7cb96193071f8a7c  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/9f  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/58/2013069d105641a1b4420a358c0fb5a26f5f8d  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/58  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/67/16b57f6f31de256a61af06b0791dd16f55438c  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/67  -- Deleting
	Deleting On Dropbox:  levcalc/.idea/modules.xml  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/index  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.idea/vcs.xml  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/logs/refs/remotes/origin/master  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/logs/refs/remotes/origin  -- Deleting
	Remote Folder Empty: /levcalc/.git/logs/refs/remotes  -- Deleting
	Remote Folder Empty: /levcalc/.git/logs/refs  -- Deleting
	Remote Folder Empty: /levcalc/.git/logs  -- Deleting
	Deleting On Dropbox:  levcalc/.git/hooks/commit-msg.sample  -- File Deleted Locally
	Deleting On Dropbox:  levcalc/.git/info/exclude  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/info  -- Deleting
	Deleting On Dropbox:  levcalc/.idea/levcalc.iml  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.idea  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/94/a25f7f4cb416c083d265558da75d457237d671  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/94  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/c7/f16da42da1cfbb2b141239819250ce47059b43  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/c7  -- Deleting
	Deleting On Dropbox:  levcalc/.git/hooks/pre-rebase.sample  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/hooks  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/91/ba864e768cba67ddb7443ece950868635d76e4  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/91  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/5a/5e256d4f08bdf731628043e6db7c1b89902977  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/5a  -- Deleting
	Deleting On Dropbox:  levcalc/.git/objects/9e/eb0d75c994cd3aec82feaec7a246184ebc2e71  -- File Deleted Locally
	Remote Folder Empty: /levcalc/.git/objects/9e  -- Deleting

Saving Local State

Sync Complete

**Comment by markhamilton1** [comment]
This appears to be a compatibility problem with an older version of Synchronator. Files and directories that start with a period are hidden, and should not have been copied to Dropbox in the first place. The bug has been fixed in the software, but I think the solution is to delete those files from your App directory on Dropbox. They will then not be downloaded from there and overwrite the ones you already have locally.
