### ISSUE TITLE
Not preserving case of grandparent directory when making directories in Pythonista

### ISSUE THREAD

**Issue by Dangthrimble** [markhamilton1/Synchronator#12]
Why does Synchronator not preserve the case of grandparent directories when making directories? Having got Synchronator working, I copied some files into the appropriate Dropbox directory on my PC and ran Synchronator. It iterated through each of the directories that needed to be made, but when making a child directory, its grandparent's name became all lower case. You can see this in these few lines from the log:

```
Updating From Dropbox

	Making Directory:  My Code

	Making Directory:  My Code/Exercism

	Making Directory:  my code/Exercism/python

	Making Directory:  my code/exercism/python/hamming
```

The net result was that I ended up with the following directories in Pythonista:

```
My Code/Exercism
my code/Exercism/python
my code/exercism/python
```

The only directory that actually had anything in it was the last one.

**Comment by markhamilton1** [comment]
Thank you for pointing this out. In debugging the issue I was making incorrect assumptions about how the dropbox API was working and have now fixed this issue in the updated version.
