### ISSUE TITLE
Dropbox File Syncronization Fail: Timeout

### ISSUE THREAD

**Issue by frankys1000** [markhamilton1/Synchronator#13]
Hi Mark, 

I have Python dropbox package (8.5.0) installed with pip through StaSh; Synchronator and DropboxSetup installed from your github repository according to your instructions and then created an App under Dropbox. Unfortunately when running Synchronator (With Run button or thru StaSh) and entering the requested access token, I always get the same error that I can't explain nor fix. Can you help? Thx for looking into it:

[~/Documents]$ python Synchronator.py
```****************************************```
```*     Dropbox File         *```
```****************************************```

Enter access token:O59MP-JcIQIAAAAAAAClh1EloLucJqlkS_hDr6BxkifbpIXqrWJd7ZbxmqEMgopz

Loading Local State

Cannot Find State File -- Creating New Local State

Updating From Dropbox

**Error: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int or float.**
[~/Documents]$

**Comment by mdmadhu** [comment]
Same issue here. Hoping someone has some advice/fix. Thanks.

**Comment by mhordern** [comment]
Me three, on iPhone 6s but not iPad Air 2

**Comment by markhamilton1** [comment]
I was able to duplicate this problem and it appears to be a dependency issue. I was able to fix the problem by deleting requests, then updating all of the dependent modules and then reinstalling requests.

The modules in question are certifi, chardet, idna, urllib3, and then requests.
