### ISSUE TITLE
How do you update the dropbox package?

### ISSUE THREAD

**Issue by andymadge** [markhamilton1/Synchronator#4]
I have version 6.4.0 in my Pythonista.  How do you update to 7.2.1+?

**Comment by andymadge** [comment]
I figured it out - you need to install Stash from https://github.com/ywangd/stash then run it and do `pip update dropbox`

**Comment by lizyn** [comment]
Not exactly. In my case, I have to install dropbox rather then updating it. When I run `pip update dropbox`, It says, "package not installed: dropbox". Any idea?

**Comment by andymadge** [comment]
Have you installed Stash first? https://github.com/ywangd/stash

After installing it, try `pip install dropbox `
