### ISSUE TITLE
How to change access token?

### ISSUE THREAD

**Issue by a11enh** [markhamilton1/Synchronator#5]
There is probably an easy solution here, but I can’t seem to find it.  If one enters the wrong access token, no files will be synced of course, and a timeout error is thrown.  (In reality it’s a time out because access wasn’t granted.)

Is there a way to re-obtain an inital state for the script run to re-enter the access token, or a simple way to alter it with the proper token?  (A note in the wiki explaining how to do this would be an excellent addition.)

**Comment by markhamilton1** [comment]
That is an excellent suggestion. I have now added a page to the wiki on Managing the token. Let me know if it helps, or it needs more details.

Thanks!
